using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedAssist.Data.Migrations
{
    /// <inheritdoc />
    public partial class RefactorBookPrimaryKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_books_numeric_id",
                table: "books");

            migrationBuilder.DropColumn(
                name: "numeric_id",
                table: "books");

            // Move the old string id into book_id, then replace id with int identity PK
            migrationBuilder.Sql("ALTER TABLE books RENAME COLUMN id TO book_id;");
            migrationBuilder.Sql("ALTER TABLE books DROP CONSTRAINT IF EXISTS \"PK_books\";");
            migrationBuilder.Sql("ALTER TABLE books ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;");

            migrationBuilder.CreateIndex(
                name: "IX_books_book_id",
                table: "books",
                column: "book_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_books_book_id",
                table: "books");

            migrationBuilder.Sql("ALTER TABLE books DROP CONSTRAINT IF EXISTS \"PK_books\";");
            migrationBuilder.Sql("ALTER TABLE books DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE books RENAME COLUMN book_id TO id;");
            migrationBuilder.Sql("ALTER TABLE books ADD PRIMARY KEY (id);");

            migrationBuilder.AddColumn<int>(
                name: "numeric_id",
                table: "books",
                type: "integer",
                nullable: false,
                defaultValue: 0)
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.CreateIndex(
                name: "IX_books_numeric_id",
                table: "books",
                column: "numeric_id",
                unique: true);
        }
    }
}
